language: go
go:
- '1.11.x'

install:
  - go get github.com/whyrusleeping/gx
  - go get github.com/whyrusleeping/gx-go
  - gx install --global
  - gx-go rw
script:
  - go test -v 

cache:
  directories:
    - $GOPATH/src/gx
