language: go
sudo: required
go:
- '1.11.x'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnfc-dev
install:
  - go get github.com/whyrusleeping/gx
  - go get github.com/whyrusleeping/gx-go
  - gx install --global
  - gx-go rw
script:
  - go test -v 

cache:
  directories:
    - $GOPATH/src/gx
